[project]
name = "searchable-screenshots"
version = "0.1.0"
description = "Make your screenshots folder searchable"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "langchain>=0.1.0",
    "langchain-community>=0.0.20",
    "langchain-ollama>=0.1.0",
    "langchain-qdrant>=0.1.0",
    "numpy>=2.3.5",
    "oneocr>=1.0.10",
    "pyside6>=6.10.1",
    "qdrant-client>=1.16.2",
    "qtawesome>=1.4.0",
    "rank-bm25>=0.2.2",
]
[tool.uv]
link-mode = "symlink"

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
]
